"""Install MCPs from the community catalog.

Two entry points:

- :func:`install_from_catalog` — fetch one MCP folder from
  ``OtoDock/community-mcps`` GitHub tarball and install it. Used by the
  admin Browse Community → Install flow and, transitively, by
  the manager-request → admin-approve flow.
- :func:`install_from_extracted_folder` — shared install pipeline. Takes
  a folder with a ``manifest.json`` and runs: validate → copy/replace →
  ``mcp_installer.install_mcp`` (npm/pip/docker) → rollback on failure →
  refresh registry. Reused by the zip-upload endpoint
  (``POST /v1/admin/mcps/install``) so both code paths share the same
  rollback + .env-regen + manifest-rescan logic.
"""

from __future__ import annotations

import asyncio
import io
import json
import logging
import re
import shutil
import tarfile
import tempfile
from pathlib import Path

import httpx
from fastapi import HTTPException

import config
from services.mcp import mcp_registry, mcp_installer

logger = logging.getLogger("claude-proxy.community-installer")

# GitHub tarball endpoint. Follows a 302 to a codeload CDN URL — httpx
# follows redirects by default. The whole repo is ~50KB right now; even at
# 10x growth it stays trivial to download for one install.
CATALOG_TARBALL_URL = (
    "https://api.github.com/repos/OtoDock/community-mcps/tarball/main"
)
TARBALL_FETCH_TIMEOUT_SECONDS = 30.0

# Runtime-only directories preserved across update. node_modules / venv are
# expensive to rebuild; patches / keys / config / screenshots are local state
# the catalog never knows about.
_PRESERVE_DIRS = {"node_modules", "venv", "patches", "keys", "config", "screenshots"}

# Generated runtime FILES (root-level) preserved across an update so their state
# survives the file-replace. ``docker-compose.override.yml`` carries the T1 subnet
# pin — keep it so the MCP's bridge subnet stays stable across updates. (The Docker
# ``.env`` is regenerated by ``_inject_mcp_env`` each start, so it isn't listed.)
_PRESERVE_FILES = {"docker-compose.override.yml"}

# Same window as the zip-upload path. Generous for npm + Playwright installs
# on a slow box; if it trips, the rollback path engages cleanly.
_INSTALL_TIMEOUT_SECONDS = 120


# ---------------------------------------------------------------------------
# Progress + off-loop filesystem helpers
# ---------------------------------------------------------------------------

# Job-level progress callback: receives ``{phase, pct, message}`` dicts. Reuses
# mcp_installer's permissive shape (sync or async callable, or None). The admin
# catalog-install background task passes a closure that writes to
# ``core.credentials.catalog_install_registry``; every other caller passes ``None`` and is
# unaffected.
ProgressCb = mcp_installer.ProgressCb


async def _emit(progress_cb: ProgressCb, phase: str, pct: int, message: str) -> None:
    """Forward one job-level progress event to ``progress_cb``. Never raises —
    a bad progress sink must not fail an install."""
    if progress_cb is None:
        return
    try:
        r = progress_cb({"phase": phase, "pct": pct, "message": message})
        if asyncio.iscoroutine(r):
            await r
    except Exception:
        logger.exception("install progress_cb raised")


def _apply_extracted_files(
    mcp_root: Path, target_dir: Path, is_update: bool, backup_dir: Path | None,
) -> None:
    """Backup (on update) + copy/replace the extracted MCP files into place.

    Synchronous filesystem work — run via ``asyncio.to_thread`` so a large
    copytree/rmtree (an update backs up the existing dir, which can hold a
    hundreds-of-MB ``node_modules``/``venv``) never stalls the event loop now
    that the install also runs as a background task. Subdirs in
    ``_PRESERVE_DIRS`` survive an update. Verbatim move of the previous inline
    logic.
    """
    if is_update and target_dir.exists() and backup_dir is not None:
        if backup_dir.exists():
            shutil.rmtree(backup_dir)
        shutil.copytree(target_dir, backup_dir)

        for item in list(target_dir.iterdir()):
            if item.name in _PRESERVE_DIRS or item.name in _PRESERVE_FILES:
                continue
            if item.is_dir():
                shutil.rmtree(item)
            else:
                item.unlink()

        for item in mcp_root.iterdir():
            dest = target_dir / item.name
            if item.is_dir():
                if item.name in _PRESERVE_DIRS and dest.exists():
                    continue
                if dest.exists():
                    shutil.rmtree(dest)
                shutil.copytree(item, dest)
            else:
                shutil.copy2(item, dest)
    elif target_dir.exists():
        # Folder exists but the MCP isn't in the registry — a data remnant
        # (e.g. ssh-server's preserved keys/ carried across a migration) or a
        # half-cleaned install. A plain copytree would FileExistsError; merge
        # instead, keeping preserved data dirs that already exist.
        for item in mcp_root.iterdir():
            dest = target_dir / item.name
            if item.is_dir():
                if item.name in _PRESERVE_DIRS and dest.exists():
                    continue
                if dest.exists():
                    shutil.rmtree(dest)
                shutil.copytree(item, dest)
            else:
                shutil.copy2(item, dest)
    else:
        shutil.copytree(mcp_root, target_dir)


def _rollback_extracted_files(target_dir: Path, backup_dir: Path) -> None:
    """Restore the pre-update backup after a failed install. Synchronous —
    run via ``asyncio.to_thread``."""
    shutil.rmtree(target_dir, ignore_errors=True)
    shutil.move(str(backup_dir), str(target_dir))


# ---------------------------------------------------------------------------
# Manifest validation — same rules as the zip-upload path used to enforce
# locally. Moved here so both flows share one source of truth.
# ---------------------------------------------------------------------------

def _validate_manifest(data: dict) -> list[str]:
    """Return a list of human-readable validation errors; empty = valid."""
    errors: list[str] = []
    for key in ("name", "label", "description", "version", "category", "server"):
        if key not in data:
            errors.append(f"Missing required field: {key}")
    if "server" in data:
        s = data["server"]
        if str(s.get("source", "")).startswith("remote:"):
            # Vendor-hosted MCP (linear/slack/zoom …) — nothing runs locally,
            # so no runtime/command; the connection needs a URL and a
            # non-stdio transport instead.
            if not s.get("url_template"):
                errors.append("Missing server.url_template (remote MCP)")
            if s.get("transport", "stdio") == "stdio":
                errors.append("Remote MCPs must declare a non-stdio transport")
        else:
            if "runtime" not in s:
                errors.append("Missing server.runtime")
            if s.get("runtime") in ("node", "python") and "command" not in s:
                errors.append("Missing server.command")
    name = data.get("name", "")
    if name and not all(c.isalnum() or c in "-_" for c in name):
        errors.append(f"Invalid name '{name}' — use alphanumeric, dash, underscore only")
    cat = data.get("category", "")
    if cat and cat not in ("core", "custom", "community"):
        errors.append(f"Invalid category '{cat}' — must be core, custom, or community")
    return errors


# ---------------------------------------------------------------------------
# Folder install — shared between zip-upload and tarball-fetch
# ---------------------------------------------------------------------------

async def install_from_extracted_folder(
    mcp_root: Path, *, progress_cb: ProgressCb = None, install_version: str | None = None,
) -> dict:
    """Install or update an MCP from an already-extracted folder.

    The folder must contain a ``manifest.json`` at its root. Subdirectories
    listed in ``_PRESERVE_DIRS`` are kept across updates so a re-install
    doesn't blow away ``node_modules`` / ``venv`` / per-instance state.

    ``progress_cb`` (optional) receives job-level ``{phase, pct, message}``
    events through the install — used by the async admin-install background job
    to drive the dashboard progress bar. Default ``None`` leaves the zip-upload
    endpoint and any other caller unchanged.

    ``install_version`` (optional) pins the exact node/python version to install
    (the update path resolves the bounded target and passes it here). When
    unset, a fresh install resolves the catalog ``server.version_constraint`` (if
    any) to the latest in-bound version, installs an already-pinned ``source``
    verbatim, or installs the bare latest. Ignored for docker/git+.

    Raises ``HTTPException`` on validation or install failure. Returns a
    dict matching the existing zip-upload endpoint's response shape so the
    frontend can reuse its install-result UI.
    """
    # `.env` files in the install archive have caused every credential leak
    # in the historical audit. Reject them — the platform generates Docker
    # MCP `.env` from manifest declarations, stdio MCPs receive env from the
    # session, and per-user/per-instance credentials live in the DB.
    env_files = [p for p in mcp_root.rglob(".env") if p.is_file()]
    if env_files:
        rel = sorted(str(p.relative_to(mcp_root)) for p in env_files)
        raise HTTPException(
            400,
            "MCP archive must not contain `.env` files. Found: "
            f"{rel}. Use `manifest.json` env declarations + DB credentials/"
            "instances layer for sensitive values. See "
            "https://github.com/OtoDock/community-mcps/blob/main/CONTRIBUTING.md "
            "for the env contract.",
        )

    manifest_path = mcp_root / "manifest.json"
    if not manifest_path.is_file():
        raise HTTPException(400, "manifest.json not found in MCP folder")

    try:
        manifest_data = json.loads(manifest_path.read_text())
    except json.JSONDecodeError as e:
        raise HTTPException(400, f"Invalid manifest.json: {e}")

    errors = _validate_manifest(manifest_data)
    if errors:
        raise HTTPException(400, f"Invalid manifest: {'; '.join(errors)}")

    mcp_name = manifest_data["name"]
    category = manifest_data["category"]
    runtime = manifest_data["server"].get("runtime", "")  # absent on remote MCPs
    source = manifest_data["server"].get("source", "")
    version = manifest_data.get("version", "unknown")

    if category != "community":
        raise HTTPException(
            400,
            "Only community MCPs can be installed via this path. Core and "
            "custom MCPs ship with the platform.",
        )

    target_parent = config.MCPS_DIR / category
    target_parent.mkdir(parents=True, exist_ok=True)

    existing = mcp_registry.get_manifest(mcp_name)
    is_update = existing is not None
    old_version = existing.version if existing else None
    # Snapshot the prior enabled state. On update we'll restore it post-scan;
    # on new install we'll force enabled=True so the admin doesn't have to
    # flip the platform-enable toggle after an explicit "install" action.
    prior_enabled = _existing_enabled_state(mcp_name) if is_update else None

    folder_name = existing.mcp_dir.name if is_update else re.sub(
        r"[^a-zA-Z0-9_-]", "-", mcp_name,
    )
    target_dir = target_parent / folder_name

    # On update: take a sibling backup for rollback, then replace only the
    # non-preserved files. On new install: just copy. All synchronous FS work
    # runs off the event loop (this function can run as a background install
    # task), so a large copytree/rmtree can't stall the loop.
    await _emit(progress_cb, "prepare", 15, "Preparing files")
    backup_dir: Path | None = None
    if is_update and target_dir.exists():
        backup_dir = target_dir.with_suffix(".bak")
    await asyncio.to_thread(
        _apply_extracted_files, mcp_root, target_dir, is_update, backup_dir,
    )

    # Run the package install (npm / pip / docker). The shared
    # ``mcp_installer`` is the same one the satellite uses.
    install_log = ""
    install_ok = True
    resolved_version = ""
    # remote: MCPs are vendor-hosted — the folder copy above IS the install
    # (manifest registration only), so skip the package-install step.
    if source and not source.startswith("remote:"):
        # Effective install source for node/python. The catalog source is unpinned
        # (`npm:pkg` / `pypi:pkg`); pick the exact version to install:
        #   • install_version given (update path) → that version;
        #   • catalog declares a version_constraint (fresh install) → latest in-bound;
        #   • source already pinned (e.g. a zip upload `npm:pkg@1.0.0`) → as-is;
        #   • otherwise → bare source (install_mcp installs the latest).
        # docker/git+ are installed verbatim (constraint/install_version ignored).
        from services.mcp import mcp_updater
        parsed = mcp_installer.parse_source(source)
        effective_source = source
        if parsed and parsed.registry in ("npm", "pypi"):
            if install_version:
                effective_source = f"{parsed.registry}:{parsed.package}@{install_version}"
            elif not parsed.version:
                constraint = manifest_data["server"].get("version_constraint", "") or ""
                if constraint:
                    target = await mcp_updater.resolve_latest_in_bound(
                        parsed.registry, parsed.package, constraint,
                    )
                    if not target:
                        if backup_dir and backup_dir.exists():
                            await asyncio.to_thread(
                                _rollback_extracted_files, target_dir, backup_dir,
                            )
                        raise HTTPException(
                            502,
                            f"No published {parsed.registry} version of "
                            f"'{parsed.package}' satisfies the catalog version "
                            f"constraint {constraint!r}.",
                        )
                    effective_source = f"{parsed.registry}:{parsed.package}@{target}"

        # Map mcp_installer's intra-step pct (npm/venv/pip, 0-100) into the job's
        # 20-80 "installing dependencies" band. A no-op for docker — install_mcp
        # returns instantly there; the real docker work (pull/start) is below.
        async def _install_progress(ev: dict) -> None:
            sub = ev.get("pct") or 0
            mapped = 20 + int(sub * 0.6)
            await _emit(
                progress_cb, "install", mapped,
                ev.get("message") or ev.get("phase") or "Installing dependencies",
            )
        try:
            result = await mcp_installer.install_mcp(
                target_dir, runtime, effective_source,
                progress_cb=_install_progress,
                uv_bin=_uv_bin_if_present(),
                timeout=_INSTALL_TIMEOUT_SECONDS,
            )
            install_ok, install_log = result.ok, result.log
            resolved_version = result.resolved_version
        except asyncio.TimeoutError:
            install_ok, install_log = False, "Install timed out"

    if not install_ok:
        if backup_dir and backup_dir.exists():
            await asyncio.to_thread(_rollback_extracted_files, target_dir, backup_dir)
        raise HTTPException(
            500,
            f"Install failed — rolled back.\n\n{install_log}",
        )

    if backup_dir and backup_dir.exists():
        await asyncio.to_thread(shutil.rmtree, backup_dir, ignore_errors=True)

    # Pin the LOCAL manifest for unpinned node/python installs (the catalog
    # carries no version for these — see services/mcp/mcp_updater.pin_local_manifest).
    # Best-effort: the install already succeeded and the backup is gone, so a pin
    # write failure must not fail the install — it self-heals on the next update.
    parsed = mcp_installer.parse_source(source) if source else None
    if parsed and parsed.registry in ("npm", "pypi") and resolved_version:
        try:
            from services.mcp import mcp_updater
            await asyncio.to_thread(
                mcp_updater.pin_local_manifest,
                target_dir, parsed.registry, parsed.package, resolved_version,
            )
            version = resolved_version
        except Exception as exc:
            logger.warning("Failed to pin local manifest for %s: %s", mcp_name, exc)
    # Never surface an empty version (unpinned catalog manifest reports "");
    # a readback miss leaves it unpinned but the UI should still show something.
    version = version or "latest"

    # Pick up the new manifest in the in-process registry, then regenerate
    # the Docker .env so the container picks up current platform values
    # without waiting for a proxy restart or enable-toggle.
    mcp_registry.scan_manifests()

    # Auto-enable on new install. On update, restore whatever the admin had
    # previously chosen (scan_manifests defaults community→disabled, which
    # would silently re-disable an MCP that was already enabled). For Docker
    # MCPs the .env regeneration below also runs only when enabled, so order
    # matters.
    from storage import mcp_store
    if is_update and prior_enabled is not None:
        await asyncio.to_thread(mcp_store.set_mcp_enabled, mcp_name, prior_enabled)
    elif not is_update:
        await asyncio.to_thread(mcp_store.set_mcp_enabled, mcp_name, True)

    refreshed = mcp_registry.get_manifest(mcp_name)

    # Default a relay-capable OAuth MCP to the OtoDock hosted relay so it works
    # out of the box. Relay-capable = the manifest declares a top-level
    # ``hosted.oauth_app`` that is available; if the relay is available it should
    # be the default (that is the whole point — no BYO OAuth app needed). We
    # persist the explicit ``_hosted_service_mode`` value rather than relying on
    # the manifest-``default_mode`` fallback (some read paths skip that fallback,
    # which is why a fresh install otherwise lands on self-managed). Only set it
    # when the admin hasn't already chosen a mode — so this never clobbers an
    # explicit choice and is a safe no-op on update.
    if (
        refreshed
        and refreshed.hosted
        and refreshed.hosted.oauth_app
        and refreshed.hosted.oauth_app.available
    ):
        existing_mode = await asyncio.to_thread(
            mcp_store.get_mcp_config_value, mcp_name, "_hosted_service_mode"
        )
        if existing_mode is None:
            await asyncio.to_thread(
                mcp_store.set_mcp_config_value, mcp_name, "_hosted_service_mode", "hosted"
            )
            logger.info("Defaulted relay-capable MCP %s to hosted OAuth", mcp_name)

    if refreshed and refreshed.server.runtime == "docker":
        try:
            from services.mcp import docker_manager
            await asyncio.to_thread(docker_manager._inject_mcp_env, refreshed)
        except Exception as exc:
            logger.warning("Failed to populate .env after install for %s: %s", mcp_name, exc)
        # T2: rewrite the compose to pull-form now (early), so a no-image Docker
        # MCP fails the install with a clear message instead of at first start.
        # Best-effort + idempotent + no-op on bare-metal T1.
        try:
            from services.mcp import compose_rewrite
            await asyncio.to_thread(compose_rewrite.ensure_pull_compose, refreshed)
        except ValueError as exc:
            raise HTTPException(
                400,
                f"'{mcp_name}' cannot be installed in Docker-Compose mode: {exc}",
            )
        except Exception as exc:
            logger.warning("Compose pre-rewrite skipped for %s: %s", mcp_name, exc)
        # T2 only: the boot-time startup_docker_mcps skips community Docker MCPs,
        # so a runtime install has no other trigger to actually start the pulled
        # container — start it here when the MCP is enabled. Best-effort: a slow
        # first pull or a transient failure doesn't fail the install (the admin
        # can retry via restart). T1 is unchanged — startup_docker_mcps / the
        # admin start it there.
        from core.config import deployment
        enabled_now = True if not is_update else bool(prior_enabled)
        # Auto-start the container after install on every self-host topology —
        # T1 bare-metal AND T2 socket-proxy; only cloud (external-pool) has no
        # local container. start_container pulls (or builds, T1 fallback) + brings
        # it up, so the slow opaque fetch shows as the "image" phase on both.
        if enabled_now and deployment.current_mode() != deployment.EXTERNAL_POOL:
            await _emit(
                progress_cb, "image", 40,
                "Fetching image — large images can take a few minutes…",
            )
            try:
                # On an UPDATE, force-recreate so the running container is
                # replaced; start_container refreshes the image either way (a
                # same-tag rebuild or moved tag wouldn't be re-pulled by a
                # plain recreate).
                started = await asyncio.to_thread(
                    docker_manager.start_container, refreshed,
                    force_recreate=is_update,
                )
                logger.info("Auto-start %s after install: ok=%s", mcp_name, started)
            except Exception as exc:
                logger.warning("Auto-start of %s after install failed: %s", mcp_name, exc)
            await _emit(progress_cb, "start", 90, "Starting container")

    await _emit(progress_cb, "finalize", 95, "Finalizing")
    return {
        "status": "updated" if is_update else "installed",
        "name": mcp_name,
        "version": version,
        "old_version": old_version,
        "runtime": runtime,
        "install_log": install_log,
    }


def _uv_bin_if_present() -> str | None:
    """Return path to ``uv`` if present, else ``None``."""
    import os
    uv = os.path.expanduser("~/.local/bin/uv")
    return uv if os.path.isfile(uv) else None


def _existing_enabled_state(mcp_name: str) -> bool | None:
    """Return the current ``mcp_state.enabled`` for an MCP, or ``None`` if no row exists."""
    from storage import mcp_store
    state = mcp_store.get_mcp_state(mcp_name)
    return state.get("enabled") if state else None


# ---------------------------------------------------------------------------
# Catalog install — fetch from GitHub, then call the shared pipeline
# ---------------------------------------------------------------------------

async def install_from_catalog(
    name: str, *, progress_cb: ProgressCb = None, install_version: str | None = None,
) -> dict:
    """Download one MCP folder from ``OtoDock/community-mcps`` and install it.

    Fetches the whole-repo tarball (small — ~50KB at the time of writing),
    extracts just the ``<name>/`` subfolder, hands it to
    :func:`install_from_extracted_folder`. Raises ``HTTPException`` on fetch
    or install failure.

    ``progress_cb`` (optional) is threaded through for live install progress;
    default ``None`` leaves the manager-request/approve caller unchanged.
    ``install_version`` (optional) pins the exact node/python version to install
    (the converge-update path passes the bounded target).
    """
    if not _is_safe_name(name):
        # Defense-in-depth — endpoint also validates, but the path is built
        # below by string interpolation against the tarball entries, so any
        # callable into this function gets the same check.
        raise HTTPException(400, f"Invalid MCP name: {name!r}")

    await _emit(progress_cb, "fetch", 5, "Downloading from catalog")
    tarball = await _fetch_catalog_tarball()

    tmp = Path(tempfile.mkdtemp(prefix="mcp-catalog-install-"))
    try:
        # Extract just the target MCP's folder. GitHub tarballs prefix every
        # path with ``<owner>-<repo>-<sha>/`` so we walk to find the entry
        # that matches ``<prefix>/<name>/``.
        mcp_root = await asyncio.to_thread(
            _extract_mcp_subfolder, tarball, name, tmp,
        )
        if mcp_root is None:
            raise HTTPException(
                404,
                f"MCP '{name}' not found in catalog tarball. The catalog may "
                "have been updated since the last list refresh.",
            )

        return await install_from_extracted_folder(
            mcp_root, progress_cb=progress_cb, install_version=install_version,
        )
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def _is_safe_name(name: str) -> bool:
    """Allow only ``[a-z0-9_-]`` so a malicious name can't escape the
    tarball-extraction path or sneak ``..`` into target paths."""
    return bool(re.fullmatch(r"[a-z0-9][a-z0-9_-]*", name))


async def _fetch_catalog_tarball() -> bytes:
    """GET the catalog repo tarball as raw bytes."""
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "otodock-platform/community-installer",
    }
    try:
        async with httpx.AsyncClient(
            timeout=TARBALL_FETCH_TIMEOUT_SECONDS,
            follow_redirects=True,
        ) as client:
            resp = await client.get(CATALOG_TARBALL_URL, headers=headers)
        resp.raise_for_status()
        return resp.content
    except httpx.HTTPError as exc:
        raise HTTPException(
            502,
            f"Could not fetch community catalog tarball: {exc}. "
            "Check network access to api.github.com / codeload.github.com.",
        )


def _extract_mcp_subfolder(tarball: bytes, mcp_name: str, dest: Path) -> Path | None:
    """Extract the catalog folder for ``mcp_name`` from the repo tarball into ``dest``.

    The folder usually shares the MCP's name, but the authoritative id is the
    ``name`` inside each folder's ``manifest.json`` and the two can differ —
    the catalog folder ``workspace-mcp`` ships manifest name
    ``google-workspace`` — so when no folder matches the name directly, fall
    back to scanning the top-level manifests for the matching name. Returns
    the path to the extracted MCP folder, or ``None`` when neither lookup
    matches.
    """
    # Tarball layout: <owner>-<repo>-<sha>/<folder>/...
    with tarfile.open(fileobj=io.BytesIO(tarball), mode="r:gz") as tf:
        # Detect the prefix dir from the first member.
        members = tf.getmembers()
        if not members:
            return None
        prefix = members[0].name.split("/", 1)[0]
        folder = mcp_name
        if not any(
            m.name == f"{prefix}/{folder}" or m.name.startswith(f"{prefix}/{folder}/")
            for m in members
        ):
            folder = _folder_for_manifest_name(tf, members, prefix, mcp_name)
            if folder is None:
                return None
        prefix_with_mcp = f"{prefix}/{folder}/"

        wanted: list[tarfile.TarInfo] = []
        for m in members:
            if m.name == f"{prefix}/{folder}" or m.name.startswith(prefix_with_mcp):
                # Strip the prefix from the entry name so extraction lands
                # under ``dest/`` directly with no nested ``<sha>/`` wrapper.
                stripped = m.name[len(prefix) + 1:]
                if not stripped:
                    continue
                # Path-traversal guard.
                if stripped.startswith("/") or ".." in Path(stripped).parts:
                    raise HTTPException(400, f"Invalid tarball entry: {m.name}")
                m_copy = tarfile.TarInfo(name=stripped)
                m_copy.type = m.type
                m_copy.mode = m.mode
                m_copy.uid = m.uid
                m_copy.gid = m.gid
                m_copy.size = m.size
                m_copy.mtime = m.mtime
                m_copy.linkname = m.linkname
                wanted.append(m_copy)
                # Extract right away while we still have the source member.
                src = tf.extractfile(m) if m.isfile() else None
                target_path = dest / stripped
                if m.isdir():
                    target_path.mkdir(parents=True, exist_ok=True)
                elif m.isfile() and src is not None:
                    target_path.parent.mkdir(parents=True, exist_ok=True)
                    with target_path.open("wb") as out:
                        shutil.copyfileobj(src, out)
                elif m.issym() or m.islnk():
                    # We don't expect symlinks in catalog MCPs. Skip rather
                    # than raise so a stray symlink doesn't block install.
                    logger.warning("Skipping link entry in catalog tarball: %s", m.name)

        if not wanted:
            return None

    mcp_dir = dest / folder
    return mcp_dir if mcp_dir.is_dir() else None


def _folder_for_manifest_name(
    tf: tarfile.TarFile, members: list, prefix: str, mcp_name: str,
) -> str | None:
    """Top-level tarball folder whose ``manifest.json`` declares ``name == mcp_name``."""
    for m in members:
        parts = m.name.split("/")
        if len(parts) == 3 and parts[2] == "manifest.json" and m.isfile():
            src = tf.extractfile(m)
            if src is None:
                continue
            try:
                data = json.loads(src.read().decode("utf-8"))
            except (ValueError, UnicodeDecodeError):
                continue
            if data.get("name") == mcp_name:
                return parts[1]
    return None


# ---------------------------------------------------------------------------
# Request orchestration — approve / reject / cancel
# ---------------------------------------------------------------------------

async def approve_request(request_id: int, admin_sub: str, admin_note: str = "") -> dict:
    """Approve an assignment request: install if needed + enable for agent.

    Returns the updated request row. Status transitions:

    - ``pending → approved → installing → installed`` on success
    - ``pending → approved → installing → install_failed`` on install error
      (the admin can retry later via the same endpoint).

    The MCP is enabled for the requesting agent (``mcp_store.add_agent_mcp``)
    only after the install completes successfully. Notifies the requester
    once the request resolves.
    """
    from storage import mcp_request_store, mcp_store

    req = await asyncio.to_thread(mcp_request_store.get_request, request_id)
    if req is None:
        raise HTTPException(404, f"Request {request_id} not found")
    if req["status"] not in ("pending", "install_failed"):
        raise HTTPException(
            409,
            f"Cannot approve request in status {req['status']!r}",
        )

    # pending → approved → installing in one shot (avoid two notifications).
    if req["status"] == "pending":
        await asyncio.to_thread(
            mcp_request_store.update_status,
            request_id, "approved", resolved_by=admin_sub, admin_note=admin_note,
        )
    req = await asyncio.to_thread(
        mcp_request_store.update_status, request_id, "installing",
    )

    mcp_name = req["mcp_name"]
    agent_slug = req["agent_slug"]

    install_log = ""
    install_failed_msg: str | None = None
    try:
        # Skip the install when the MCP is already on disk and at the current
        # catalog version — the registry's ``get_manifest`` returns ``None``
        # only when the folder is absent. Serialize on the per-MCP install lock
        # so a concurrent direct admin install of the same MCP can't race this
        # on the install dir; re-check inside the lock (the other install may
        # have just landed it while we waited, in which case we no-op).
        from core.credentials import catalog_install_registry
        async with catalog_install_registry.lock_for(mcp_name):
            if mcp_registry.get_manifest(mcp_name) is None:
                install_result = await install_from_catalog(mcp_name)
                install_log = install_result.get("install_log", "")
            else:
                install_log = "Already installed — skipping fetch + dependency install."
    except HTTPException as exc:
        install_failed_msg = exc.detail if isinstance(exc.detail, str) else str(exc.detail)
    except Exception as exc:
        logger.exception("Unexpected install error for %s", mcp_name)
        install_failed_msg = f"{type(exc).__name__}: {exc}"

    if install_failed_msg:
        updated = await asyncio.to_thread(
            mcp_request_store.update_status,
            request_id, "install_failed",
            install_log=install_failed_msg,
        )
        # ``install_failed`` is non-terminal (admin may retry) — don't fire
        # the batch-complete roll-up here; only the per-request failure
        # notification, which the batched path also wants to receive so the
        # admin sees the error inline.
        await _notify_request_failed(updated)
        return updated

    # Install OK → assign the MCP to the agent. ``add_agent_mcp`` is
    # idempotent so a re-request after a previous installed state is safe.
    await asyncio.to_thread(mcp_store.add_agent_mcp, agent_slug, mcp_name)

    # For explicit-mode MCPs (prometheus, ssh-server, unifi-network, etc.),
    # the manager-enabled flag alone isn't enough — the runtime only
    # delivers env to an agent if at least one ``mcp_instances`` row
    # authorizes them. Make sure that's true before declaring success.
    instance_status, instance_detail = await asyncio.to_thread(
        _ensure_agent_authorized_for_instance_mcp, mcp_name, agent_slug,
    )
    if instance_status == "no_instances":
        # Roll the agent_mcps assignment back so the manager UI doesn't
        # show a non-functional row. The install itself is fine; only
        # per-agent authorization is missing.
        await asyncio.to_thread(mcp_store.remove_agent_mcp, agent_slug, mcp_name)
        admin_guidance = (
            f"MCP '{mcp_name}' requires an instance configuration before it "
            f"can be authorized for an agent. Create an instance via "
            f"Admin → MCP Servers → {mcp_name} → Instances (give it credentials "
            f"and optionally tick 'Assign to all agents'), then retry this "
            f"approval."
        )
        updated = await asyncio.to_thread(
            mcp_request_store.update_status,
            request_id, "install_failed",
            install_log=admin_guidance,
        )
        await _notify_request_failed(updated)
        return updated

    if instance_detail:
        install_log = (install_log + "\n" if install_log else "") + instance_detail

    updated = await asyncio.to_thread(
        mcp_request_store.update_status,
        request_id, "installed",
        resolved_by=admin_sub,
        install_log=install_log,
    )
    # Batched rows: suppress the per-request approve notification — the
    # requester gets a single roll-up via _maybe_notify_batch_complete once
    # every row in the batch reaches a terminal state.
    if updated.get("batch_id"):
        await _maybe_notify_batch_complete(updated)
    else:
        await _notify_request_approved(updated)
    return updated


def _ensure_agent_authorized_for_instance_mcp(
    mcp_name: str, agent_slug: str,
) -> tuple[str, str]:
    """Make sure an explicit-mode MCP authorizes ``agent_slug`` via at least one
    instance. No-op for non-explicit (auto-mode) MCPs.

    Returns (status, human_log) where status is one of:

    - ``"not_applicable"`` — MCP is auto-mode; nothing to do.
    - ``"assigned_to_all"`` — a catch-all instance already authorizes everyone.
    - ``"already_authorized"`` — agent was already in some instance's list.
    - ``"added_to_first"`` — agent was attached to the lowest-id instance
      (matches the runtime precedence in
      :func:`mcp_store.get_instance_for_agent_env_delivery`). Admin can move
      the agent to a different instance via the Instances UI if desired.
    - ``"no_instances"`` — explicit-mode MCP with zero instances. Caller
      should treat this as a soft failure and prompt the admin to create
      one before retrying.

    The ``human_log`` is a one-line description suitable for appending to
    the request's ``install_log``.
    """
    from storage import mcp_store

    manifest = mcp_registry.get_manifest(mcp_name)
    # ``getattr`` with default so test-stub manifests (bare ``object()``)
    # naturally fall through to "not applicable" rather than raising.
    if not manifest or getattr(manifest, "assignment_mode", "auto") != "explicit":
        return ("not_applicable", "")

    instances = mcp_store.get_mcp_instances(mcp_name)
    if not instances:
        return ("no_instances", "")

    if any(i["assigned_to_all"] for i in instances):
        return ("assigned_to_all", f"Authorized via catch-all instance.")

    if any(agent_slug in i["agents"] for i in instances):
        return ("already_authorized", f"Agent already attached to an instance.")

    target = sorted(instances, key=lambda i: i["id"])[0]
    mcp_store.add_agent_to_instance(target["id"], agent_slug)
    return (
        "added_to_first",
        f"Attached agent to instance '{target['instance_name']}' "
        f"(lowest id; admin can reassign via Instances UI).",
    )


async def reject_request(request_id: int, admin_sub: str, admin_note: str = "") -> dict:
    """Reject a pending request; notifies the requester with the admin's note."""
    from storage import mcp_request_store
    req = await asyncio.to_thread(mcp_request_store.get_request, request_id)
    if req is None:
        raise HTTPException(404, f"Request {request_id} not found")
    if req["status"] != "pending":
        raise HTTPException(409, f"Cannot reject request in status {req['status']!r}")

    updated = await asyncio.to_thread(
        mcp_request_store.update_status,
        request_id, "rejected",
        resolved_by=admin_sub, admin_note=admin_note,
    )
    if updated.get("batch_id"):
        await _maybe_notify_batch_complete(updated)
    else:
        await _notify_request_rejected(updated)
    return updated


async def cancel_request(request_id: int, user_sub: str) -> dict:
    """Cancel an open pending request. Only the original requester may cancel."""
    from storage import mcp_request_store
    req = await asyncio.to_thread(mcp_request_store.get_request, request_id)
    if req is None:
        raise HTTPException(404, f"Request {request_id} not found")
    if req["requested_by"] != user_sub:
        raise HTTPException(403, "Only the original requester can cancel")
    if req["status"] != "pending":
        raise HTTPException(409, f"Cannot cancel request in status {req['status']!r}")

    updated = await asyncio.to_thread(
        mcp_request_store.update_status,
        request_id, "cancelled",
        resolved_by=user_sub,
    )
    if updated.get("batch_id"):
        await _maybe_notify_batch_complete(updated)
    return updated


# ---------------------------------------------------------------------------
# Notification dispatch
# ---------------------------------------------------------------------------

async def notify_request_created(request: dict) -> None:
    """Notify every admin that a new MCP request landed.

    Batched-request rows (``batch_id`` populated by a community-agent install
    cascade) are skipped — the caller will fire a single combined
    notification via :func:`notify_batch_created`. Lone requests (e.g. via
    ``mcps-mcp`` or the Browse drawer) still fire one notification per admin
    per request, the legacy behavior."""
    if request.get("batch_id"):
        return
    admin_subs = await asyncio.to_thread(_list_admin_subs)
    if not admin_subs:
        return
    from services.notifications import notification_manager
    requester = _format_requester(request)
    reason = (request.get("reason") or "").strip()
    reason_line = f"\n\n_Reason:_ {reason}" if reason else ""
    for sub in admin_subs:
        await notification_manager.fire_notification(
            title="MCP request pending",
            body=(
                f"{requester} requested **{request['mcp_name']}** for agent "
                f"**{request['agent_slug']}**. Review in Admin → MCP Requests."
                f"{reason_line}"
            ),
            severity="info",
            scope="user",
            target=sub,
            source="mcp",
            source_id=str(request["id"]),
        )


async def notify_batch_created(
    batch_id: str,
    requester_sub: str,
    target_agent_slug: str,
    template_slug: str,
) -> None:
    """Fire one combined notification per admin for a community-agent
    install batch. Skips the requester if they happen to be an admin (admin
    self-installs auto-approve inline anyway — they don't need to be told).
    """
    from storage import mcp_request_store

    rows = await asyncio.to_thread(mcp_request_store.list_requests_by_batch, batch_id)
    if not rows:
        return
    admin_subs = await asyncio.to_thread(_list_admin_subs)
    admin_subs = [s for s in admin_subs if s != requester_sub]
    if not admin_subs:
        return
    from services.notifications import notification_manager
    requester = _format_requester(rows[0])
    summary_lines = []
    for row in rows:
        reason_blurb = f" — _{row['reason']}_" if (row.get("reason") or "").strip() else ""
        summary_lines.append(f"- **{row['mcp_name']}**{reason_blurb}")
    body = (
        f"{requester} wants to install community agent **{template_slug}** "
        f"as `{target_agent_slug}`. This requires admin action on "
        f"{len(rows)} MCP{'s' if len(rows) != 1 else ''}:\n\n"
        + "\n".join(summary_lines)
        + "\n\nReview in Admin → MCP Requests."
    )
    title = (
        f"Community agent install: {len(rows)} MCP"
        f"{'s' if len(rows) != 1 else ''} need approval"
    )
    for sub in admin_subs:
        await notification_manager.fire_notification(
            title=title,
            body=body,
            severity="info",
            scope="user",
            target=sub,
            source="mcp",
            source_id=f"batch:{batch_id}",
        )


async def _maybe_notify_batch_complete(request: dict) -> None:
    """Called after a request transitions to a terminal state. If the request
    is part of a batch AND every row in the batch is now terminal, fire ONE
    follow-up notification to the requester summarizing the outcome.

    Per-MCP approve/reject notifications are suppressed for batched rows —
    the requester gets a single roll-up instead.
    """
    batch_id = request.get("batch_id")
    if not batch_id:
        return
    from storage import mcp_request_store

    all_done = await asyncio.to_thread(
        mcp_request_store.all_in_batch_terminal, batch_id,
    )
    if not all_done:
        return
    rows = await asyncio.to_thread(
        mcp_request_store.list_requests_by_batch, batch_id,
    )
    if not rows:
        return
    from services.notifications import notification_manager

    requester = rows[0]["requested_by"]
    agent_slug = rows[0]["agent_slug"]
    installed = [r for r in rows if r["status"] == "installed"]
    rejected = [r for r in rows if r["status"] == "rejected"]
    cancelled = [r for r in rows if r["status"] == "cancelled"]

    lines = [f"Your community agent **{agent_slug}** is ready."]
    lines.append(
        f"{len(installed)}/{len(rows)} MCP{'s' if len(rows) != 1 else ''} approved."
    )
    if rejected:
        names = ", ".join(f"**{r['mcp_name']}**" for r in rejected)
        lines.append(f"\nRejected: {names}")
        for r in rejected:
            if (r.get("admin_note") or "").strip():
                lines.append(f"- _{r['mcp_name']}_: {r['admin_note']}")
    if cancelled:
        names = ", ".join(f"**{r['mcp_name']}**" for r in cancelled)
        lines.append(f"\nCancelled: {names}")

    severity = "info" if not (rejected or cancelled) else "warning"
    await notification_manager.fire_notification(
        title=f"Community agent {agent_slug}: setup complete",
        body="\n".join(lines),
        severity=severity,
        scope="user",
        target=requester,
        source="mcp",
        source_id=f"batch:{batch_id}",
    )


def _format_requester(request: dict) -> str:
    """Human-readable requester label for notification bodies.

    Falls back to ``Manager`` when no joined-user columns are present (e.g.
    deleted user account), or to the email when ``name`` is empty.
    """
    name = (request.get("requested_by_name") or "").strip()
    email = (request.get("requested_by_email") or "").strip()
    if name and email:
        return f"**{name}** ({email})"
    if name:
        return f"**{name}**"
    if email:
        return f"**{email}**"
    return "A manager"


async def _notify_request_approved(request: dict) -> None:
    from services.notifications import notification_manager
    await notification_manager.fire_notification(
        title="MCP request approved",
        body=(
            f"**{request['mcp_name']}** is installed and enabled for agent "
            f"**{request['agent_slug']}**."
        ),
        severity="info",
        scope="user",
        target=request["requested_by"],
        source="mcp",
        source_id=str(request["id"]),
    )


async def _notify_request_rejected(request: dict) -> None:
    from services.notifications import notification_manager
    note = request.get("admin_note") or ""
    body = f"Request for **{request['mcp_name']}** on agent **{request['agent_slug']}** was rejected."
    if note:
        body += f"\n\nAdmin note: {note}"
    await notification_manager.fire_notification(
        title="MCP request rejected",
        body=body,
        severity="warning",
        scope="user",
        target=request["requested_by"],
        source="mcp",
        source_id=str(request["id"]),
    )


async def _notify_request_failed(request: dict) -> None:
    from services.notifications import notification_manager
    log_excerpt = (request.get("install_log") or "")[:300]
    body = (
        f"Install failed for **{request['mcp_name']}** on agent "
        f"**{request['agent_slug']}**. The admin can retry from MCP Requests."
    )
    if log_excerpt:
        body += f"\n\n```\n{log_excerpt}\n```"
    # Notify both the requester and admins so neither side has to chase the
    # failure manually.
    targets = {request["requested_by"]}
    admin_subs = await asyncio.to_thread(_list_admin_subs)
    targets.update(admin_subs)
    for sub in targets:
        await notification_manager.fire_notification(
            title="MCP install failed",
            body=body,
            # Platform severity vocabulary is info/success/warning/danger —
            # "error" renders unstyled and plays no sound.
            severity="warning",
            scope="user",
            target=sub,
            source="mcp",
            source_id=str(request["id"]),
        )


def _list_admin_subs() -> list[str]:
    """Return every admin user's ``sub``."""
    from storage.pg import get_conn
    with get_conn() as conn:
        rows = conn.execute(
            "SELECT sub FROM users WHERE role='admin'",
        ).fetchall()
        return [r["sub"] for r in rows]
