"""Git-based audit trail for agent config, knowledge, + per-user context.

Three repo classes per agent:
  - ``agents/{slug}/config/``                    (prompt.md, context/ docs)
  - ``agents/{slug}/knowledge/``                 (incl. memory/ topic files)
  - ``agents/{slug}/users/{username}/context/``  (user docs + memory/)

Auto-init on first write; auto-commit per write (memory-tool ops, manager
workspace edits, admin reverts). Shell out to ``git`` directly —
no GitPython dependency, ``git`` is already in the bash allowlist.

All functions sync (called from ``asyncio.to_thread`` in handlers).
"""

from __future__ import annotations

import logging
import re
import subprocess
from pathlib import Path
from typing import Any

logger = logging.getLogger("claude-proxy.git-writer")

# Commit identifiers reaching `git show` / `git checkout` MUST be plain hex
# SHAs. Anything else (a leading `-`, e.g. `--output=/etc/foo`) would be parsed
# by git as an OPTION rather than a revision — argument injection → arbitrary
# file write. Callers always pass a SHA from the log; symbolic refs are
# intentionally not accepted at these sinks.
_COMMIT_SHA_RE = re.compile(r"^[0-9a-fA-F]{4,64}$")

_AUTHOR_NAME = "otodock-system"
_AUTHOR_EMAIL = "system@otodock"
_GITIGNORE_TEMPLATE = (
    "# Auto-generated by otodock\n"
    "*.tmp\n"
    "*.bak\n"
    ".~*\n"
    "__pycache__/\n"
)
_SUBPROC_TIMEOUT = 10  # seconds


# ---------------------------------------------------------------------------
# Repo init + writes
# ---------------------------------------------------------------------------


def init_if_missing(repo_dir: Path) -> bool:
    """``git init`` ``repo_dir`` + write a default ``.gitignore``. Returns
    True if a new repo was created. Idempotent — no-op if ``.git`` exists.
    """
    repo_dir.mkdir(parents=True, exist_ok=True)
    if (repo_dir / ".git").exists():
        return False
    try:
        subprocess.run(
            ["git", "init", "-q", "-b", "main"],
            cwd=repo_dir, check=True, timeout=_SUBPROC_TIMEOUT,
        )
        gitignore = repo_dir / ".gitignore"
        if not gitignore.exists():
            gitignore.write_text(_GITIGNORE_TEMPLATE)
        # Bootstrap commit so subsequent ``git log`` works even before any
        # tracked file lands.
        _commit_file(repo_dir, ".gitignore", "init")
        return True
    except Exception:
        logger.exception("git init failed for %s", repo_dir)
        return False


def commit_file(repo_dir: Path, file_path: Path, message: str) -> str | None:
    """Stage + commit ``file_path`` (relative to ``repo_dir`` or absolute).
    Returns the resulting commit sha (short), or None on failure.

    Idempotent on no-op commits — returns the current HEAD sha if there
    were no changes to commit.
    """
    init_if_missing(repo_dir)
    try:
        rel = (
            file_path.relative_to(repo_dir)
            if file_path.is_absolute()
            else file_path
        )
    except ValueError:
        logger.warning("commit_file: path %s not under repo %s",
                       file_path, repo_dir)
        return None
    return _commit_file(repo_dir, str(rel), message)


def commit_paths(repo_dir: Path, paths: list[Path | str], message: str) -> str | None:
    """Stage + commit several paths as ONE commit. Used by memory ops where a
    single logical write touches multiple files (topic + regenerated index,
    or a rename's old + new path — ``git add`` stages deletions too).
    Returns the resulting commit sha, or None on failure.
    """
    init_if_missing(repo_dir)
    rels: list[str] = []
    for p in paths:
        path = Path(p)
        try:
            rels.append(str(
                path.relative_to(repo_dir) if path.is_absolute() else path
            ))
        except ValueError:
            logger.warning("commit_paths: path %s not under repo %s", p, repo_dir)
            return None
    if not rels:
        return None
    try:
        subprocess.run(
            ["git", "add", "--"] + rels,
            cwd=repo_dir, check=True, timeout=_SUBPROC_TIMEOUT,
        )
        return _commit_staged(repo_dir, message)
    except Exception:
        logger.exception("commit_paths failed for %s %s", repo_dir, rels)
        return None


def _commit_file(repo_dir: Path, relative_path: str, message: str) -> str | None:
    try:
        subprocess.run(
            ["git", "add", relative_path],
            cwd=repo_dir, check=True, timeout=_SUBPROC_TIMEOUT,
        )
        return _commit_staged(repo_dir, message)
    except Exception:
        logger.exception("commit_file failed for %s/%s", repo_dir, relative_path)
        return None


def _commit_staged(repo_dir: Path, message: str) -> str | None:
    """Commit whatever is staged. Idempotent on no-op (returns HEAD sha)."""
    result = subprocess.run(
        [
            "git",
            "-c", f"user.name={_AUTHOR_NAME}",
            "-c", f"user.email={_AUTHOR_EMAIL}",
            "commit",
            "--allow-empty",
            "-m", message,
        ],
        cwd=repo_dir,
        capture_output=True, timeout=_SUBPROC_TIMEOUT,
    )
    if result.returncode not in (0, 1):
        logger.warning(
            "git commit failed in %s: %s",
            repo_dir, result.stderr.decode(errors="replace"),
        )
    return _head_sha(repo_dir)


# ---------------------------------------------------------------------------
# Read API (used by dashboard git tab)
# ---------------------------------------------------------------------------


def log(repo_dir: Path, limit: int = 50, path: str | None = None) -> list[dict[str, Any]]:
    """Return up to ``limit`` recent commits. ``path``, if given, scopes
    the log to a single file (relative to repo_dir).
    """
    if not (repo_dir / ".git").exists():
        return []
    args = [
        "git", "log",
        f"--max-count={int(limit)}",
        "--pretty=format:%H%x09%aI%x09%an%x09%s",
    ]
    if path:
        args += ["--", path]
    try:
        result = subprocess.run(
            args, cwd=repo_dir, capture_output=True,
            check=True, timeout=_SUBPROC_TIMEOUT, text=True,
        )
        out: list[dict[str, Any]] = []
        for line in result.stdout.splitlines():
            parts = line.split("\t", 3)
            if len(parts) != 4:
                continue
            sha, date, author, subject = parts
            out.append({
                "sha": sha, "short_sha": sha[:8],
                "date": date, "author": author, "subject": subject,
            })
        return out
    except Exception:
        logger.exception("git log failed for %s", repo_dir)
        return []


def diff(repo_dir: Path, commit: str, path: str | None = None) -> str:
    """Return ``git show`` output for ``commit`` (optionally scoped to one
    file). Returns the diff body as text.
    """
    if not (repo_dir / ".git").exists():
        return ""
    if not _COMMIT_SHA_RE.match(commit):
        logger.warning("git diff: rejected non-SHA commit %r", commit)
        return ""
    args = ["git", "show", "--no-color", "--end-of-options", commit]
    if path:
        args += ["--", path]
    try:
        result = subprocess.run(
            args, cwd=repo_dir, capture_output=True,
            check=True, timeout=_SUBPROC_TIMEOUT, text=True,
        )
        return result.stdout
    except Exception:
        logger.exception("git show failed for %s @ %s", repo_dir, commit)
        return ""


def revert_file_to(
    repo_dir: Path, commit: str, file_path: Path,
    *, message: str | None = None,
) -> str | None:
    """``git checkout {commit} -- file_path`` then commit. Returns new HEAD.
    Used by the admin "Revert to commit X" button.
    """
    if not (repo_dir / ".git").exists():
        return None
    if not _COMMIT_SHA_RE.match(commit):
        logger.warning("git revert: rejected non-SHA commit %r", commit)
        return None
    try:
        rel = (
            file_path.relative_to(repo_dir)
            if file_path.is_absolute()
            else file_path
        )
    except ValueError:
        logger.warning("revert_file_to: path %s not under repo %s",
                       file_path, repo_dir)
        return None
    try:
        subprocess.run(
            # `commit` is validated to a bare hex SHA above, so it can never be
            # an option — no `--end-of-options` needed here (and it conflicts
            # with the `--` pathspec separator on `git checkout`).
            ["git", "checkout", commit, "--", str(rel)],
            cwd=repo_dir, check=True, timeout=_SUBPROC_TIMEOUT,
        )
    except Exception:
        logger.exception("git checkout failed for %s @ %s", file_path, commit)
        return None
    return _commit_file(
        repo_dir, str(rel),
        message or f"revert {rel} to {commit[:8]}",
    )


def _head_sha(repo_dir: Path) -> str | None:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=repo_dir, capture_output=True,
            check=True, timeout=_SUBPROC_TIMEOUT, text=True,
        )
        return result.stdout.strip()
    except Exception:
        return None
