#!/bin/bash
# Setup script for OtoDock Proxy
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PLATFORM_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$SCRIPT_DIR"

echo "=== OtoDock Proxy Setup ==="

# 1. Check prerequisites
echo "[1/4] Checking prerequisites..."

if ! command -v claude &>/dev/null; then
    echo "WARNING: 'claude' CLI not found — needed for Claude execution layer"
fi

if ! command -v python3 &>/dev/null; then
    echo "ERROR: python3 not found"
    exit 1
fi
echo "  python3: $(python3 --version)"

if ! command -v node &>/dev/null; then
    echo "ERROR: node not found — required for Node-based MCP servers (email-server, ssh-server, prometheus, nextcloud, uptime-kuma)"
    echo "  Install via your distro package manager (apt/dnf) so 'node' lives under /usr/."
    echo "  nvm/fnm/volta installs put node under ~/, which is NOT mounted in the agent sandbox."
    echo "  If you must use a version manager, symlink the binary: sudo ln -s \"\$(which node)\" /usr/local/bin/node"
    exit 1
fi
node_path="$(readlink -f "$(command -v node)")"
case "$node_path" in
    /usr/*|/usr/local/*)
        echo "  node: $(node --version) at $node_path"
        ;;
    *)
        echo "ERROR: node at $node_path is outside /usr/ — sandboxed MCPs won't find it"
        echo "  Symlink it: sudo ln -s \"$node_path\" /usr/local/bin/node"
        exit 1
        ;;
esac

if ! command -v uv &>/dev/null && [ ! -x "$HOME/.local/bin/uv" ]; then
    echo "WARNING: uv not found — required for Python MCPs that need a non-system Python version (e.g. ha-mcp)"
    echo "  Install: curl -LsSf https://astral.sh/uv/install.sh | sh"
fi

# Docker-MCP networking: OtoDock pins the subnet of every per-MCP bridge it
# creates on bare-metal (T1) to a private /24 from OTODOCK_MCP_ADDRESS_POOL
# (default 10.201.0.0/16) — see services/compose_rewrite.ensure_t1_override — so
# NO host-level Docker `default-address-pools` config is needed for OtoDock to be
# LAN-safe. Override the pool in config.env if 10.201.0.0/16 overlaps your LAN/VPN.

# 2. Set up Python venv
echo "[2/4] Setting up Python virtual environment..."
if [ ! -d "venv" ]; then
    if python3 -m venv venv 2>/dev/null; then
        echo "  Created venv"
    else
        echo "  python3-venv not available, using --without-pip workaround..."
        python3 -m venv --without-pip venv
        curl -sS https://bootstrap.pypa.io/get-pip.py | venv/bin/python3 >/dev/null 2>&1
        echo "  Created venv with bootstrapped pip"
    fi
else
    echo "  venv already exists"
fi

# 3. Install dependencies
echo "[3/4] Installing Python dependencies..."
venv/bin/pip install --quiet -r requirements.txt
# The proxy imports the lean `oto-audio` CORE (cloud STT/TTS for chat audio +
# phone config). It's an editable local package, NOT a requirements.txt pin, so
# install it explicitly (base only — the heavy on-box `[localmodels]` ONNX stack
# is phone-only). Without this the proxy crashes at boot: `No module named
# 'audio'` (app.py imports api.audio → audio.providers).
venv/bin/pip install --quiet -e "$PLATFORM_ROOT/audio"
echo "  Done"

# 4. Generate config.env DB credentials if needed
echo "[4/4] Checking config.env..."
CONFIG_ENV="$PLATFORM_ROOT/config.env"
# Keyed on the VARIABLES, not file existence: a partial config.env (rsync'd
# tree, hand-seeded JWT_SECRET) must still gain DB creds or the bundled
# postgres fails closed on its ${POSTGRES_PASSWORD:?}. Existing values are
# never rewritten. The proxy auto-generates the REST of the secrets
# (PROXY_API_KEY, JWT_SECRET, …) into this file on first start.
if [ ! -f "$CONFIG_ENV" ]; then
    {
        echo "# Auto-generated by proxy/setup.sh on first install."
        echo "# Copy further settings from config.env.example as needed."
    } > "$CONFIG_ENV"
fi
if ! grep -q '^POSTGRES_PASSWORD=..*' "$CONFIG_ENV"; then
    if grep -q '^DATABASE_URL=..*' "$CONFIG_ENV"; then
        # DATABASE_URL exists without POSTGRES_PASSWORD: reuse its embedded
        # password so the bundled postgres inits to match.
        PGPW="$(sed -n 's|^DATABASE_URL=postgresql://[^:]*:\([^@]*\)@.*|\1|p' "$CONFIG_ENV")"
    else
        PGPW="$(python3 -c 'import secrets; print(secrets.token_urlsafe(24))')"
    fi
    if [ -n "$PGPW" ]; then
        echo "POSTGRES_PASSWORD=$PGPW" >> "$CONFIG_ENV"
        echo "  Added POSTGRES_PASSWORD to config.env."
    else
        echo "  WARNING: DATABASE_URL is set but carries no parsable password —"
        echo "  set POSTGRES_PASSWORD in config.env manually (the bundled postgres needs it)."
    fi
fi
if ! grep -q '^DATABASE_URL=..*' "$CONFIG_ENV"; then
    PGPW="$(grep -m1 '^POSTGRES_PASSWORD=' "$CONFIG_ENV" | cut -d= -f2-)"
    echo "DATABASE_URL=postgresql://otodock:$PGPW@localhost:5432/otodock" >> "$CONFIG_ENV"
    echo "  Added DATABASE_URL to config.env."
    echo "  (Docker proxy deploys: override DATABASE_URL host to otodock-postgres:5432.)"
fi
echo "  Remaining secrets auto-generate on first proxy start."

echo ""
echo "=== Setup Complete ==="
echo ""
echo "To run manually:"
echo "  cd $SCRIPT_DIR && venv/bin/python app.py"
echo ""
echo "To install as systemd service:"
echo "  Edit proxy.service — set User, Group, and paths"
echo "  sudo cp proxy.service /etc/systemd/system/otodock-proxy.service"
echo "  sudo systemctl daemon-reload"
echo "  sudo systemctl enable otodock-proxy"
echo "  sudo systemctl start otodock-proxy"
echo ""
echo "Health check: curl http://localhost:8400/health"
